#!/usr/bin/env python

data=['0>Total, All Occupations',
'1>Management, Business, and Financial Occupations',
'2>Management Occupations',
'3>Top Executives',
'4>Chief Executives',
'4>General and Operations Managers',
'4>Legislators',
'3>Advertising, Marketing, Promotions, Public Relations, and Sales Managers',
'4>Advertising and Promotions Managers',
'4>Marketing and Sales Managers',
'5>Marketing Managers',
'5>Sales Managers',
'4>Public Relations and Fundraising Managers',
'3>Operations Specialties Managers',
'4>Administrative Services Managers',
'4>Computer and Information Systems Managers',
'4>Financial Managers',
'4>Industrial Production Managers',
'4>Purchasing Managers',
'4>Transportation, Storage, and Distribution Managers',
'4>Compensation and Benefits Managers',
'4>Human Resources Managers',
'4>Training and Development Managers',
'3>Other Management Occupations',
'4>Farmers, Ranchers, and Other Agricultural Managers',
'4>Construction Managers',
'4>Education Administrators',
'5>Education Administrators, Preschool and Childcare Center/Program',
'5>Education Administrators, Elementary and Secondary School',
'5>Education Administrators, Postsecondary',
'5>Education Administrators, All Other',
'4>Architectural and Engineering Managers',
'4>Food Service Managers',
'4>Gaming Managers',
'4>Lodging Managers',
'4>Medical and Health Services Managers',
'4>Natural Sciences Managers',
'4>Postmasters and Mail Superintendents',
'4>Property, Real Estate, and Community Association Managers',
'4>Social and Community Service Managers',
'4>Emergency Management Directors',
'4>Managers, All Other',
'2>Business and Financial Operations Occupations',
'3>Business Operations Specialists',
'4>Agents and Business Managers of Artists, Performers, and Athletes',
'4>Buyers and Purchasing Agents',
'5>Buyers and Purchasing Agents, Farm Products',
'5>Wholesale and Retail Buyers, Except Farm Products',
'5>Purchasing Agents, Except Wholesale, Retail, and Farm Products',
'4>Claims Adjusters, Appraisers, Examiners, and Investigators',
'5>Claims Adjusters, Examiners, and Investigators',
'5>Insurance Appraisers, Auto Damage',
'4>Compliance Officers',
'4>Cost Estimators',
'4>Human Resources Workers',
'5>Farm Labor Contractors',
'5>Human Resources, Training, and Labor Relations Specialists, All Other',
'4>Logisticians',
'4>Management Analysts',
'4>Meeting, Convention, and Event Planners',
'4>Compensation, Benefits, and Job Analysis Specialists',
'4>Training and Development Specialists',
'4>Market Research Analysts and Marketing Specialists',
'4>Business Operations Specialists, All Other',
'3>Financial Specialists',
'4>Accountants and Auditors',
'4>Appraisers and Assessors of Real Estate',
'4>Budget Analysts',
'4>Credit Analysts',
'4>Financial Analysts and Advisors',
'5>Financial Analysts',
'5>Personal Financial Advisors',
'5>Insurance Underwriters',
'4>Financial Examiners',
'4>Credit Counselors and Loan Officers',
'5>Credit Counselors',
'5>Loan Officers',
'4>Tax Examiners, Collectors and Preparers, and Revenue Agents',
'5>Tax Examiners and Collectors, and Revenue Agents',
'5>Tax Preparers',
'4>Financial Specialists, All Other',
'1>Computer, Engineering, and Science Occupations',
'2>Computer and Mathematical Occupations',
'3>Computer Occupations',
'4>Computer and Information Research Scientists',
'4>Computer Systems Analysts',
'4>Software Developers and Programmers',
'5>Computer Programmers',
'5>Software Developers, Applications',
'5>Software Developers, Systems Software',
'4>Database and Systems Administrators and Network Architects',
'5>Database Administrators',
'5>Network and Computer Systems Administrators',
'4>Computer Support Specialists',
'4>Information Security Analysts, Web Developers, and Computer Network Architects',
'4>Computer Occupations, All Other',
'3>Mathematical Science Occupations',
'4>Actuaries',
'4>Mathematicians',
'4>Operations Research Analysts',
'4>Statisticians',
'4>Miscellaneous Mathematical Science Occupations',
'5>Mathematical Technicians',
'5>Mathematical Science Occupations, All Other',
'2>Architecture and Engineering Occupations',
'3>Architects, Surveyors, and Cartographers',
'4>Architects, Except Naval',
'5>Architects, Except Landscape and Naval',
'5>Landscape Architects',
'4>Surveyors, Cartographers, and Photogrammetrists',
'5>Cartographers and Photogrammetrists',
'5>Surveyors',
'3>Engineers',
'4>Aerospace Engineers',
'4>Agricultural Engineers',
'4>Biomedical Engineers',
'4>Chemical Engineers',
'4>Civil Engineers',
'4>Computer Hardware Engineers',
'4>Electrical and Electronics Engineers',
'5>Electrical Engineers',
'5>Electronics Engineers, Except Computer',
'4>Environmental Engineers',
'4>Industrial Engineers, Including Health and Safety',
'5>Health and Safety Engineers, Except Mining Safety Engineers and Inspectors',
'5>Industrial Engineers',
'4>Marine Engineers and Naval Architects',
'4>Materials Engineers',
'4>Mechanical Engineers',
'4>Mining and Geological Engineers, Including Mining Safety Engineers',
'4>Nuclear Engineers',
'4>Petroleum Engineers',
'4>Engineers, All Other',
'3>Drafters, Engineering Technicians, and Mapping Technicians',
'4>Drafters',
'5>Architectural and Civil Drafters',
'5>Electrical and Electronics Drafters',
'5>Mechanical Drafters',
'5>Drafters, All Other',
'4>Engineering Technicians, Except Drafters',
'5>Aerospace Engineering and Operations Technicians',
'5>Civil Engineering Technicians',
'5>Electrical and Electronics Engineering Technicians',
'5>Electro-Mechanical Technicians',
'5>Environmental Engineering Technicians',
'5>Industrial Engineering Technicians',
'5>Mechanical Engineering Technicians',
'5>Engineering Technicians, Except Drafters, All Other',
'4>Surveying and Mapping Technicians',
'2>Life, Physical, and Social Science Occupations',
'3>Life Scientists',
'4>Agricultural and Food Scientists',
'5>Animal Scientists',
'5>Food Scientists and Technologists',
'5>Soil and Plant Scientists',
'4>Biological Scientists',
'5>Biochemists and Biophysicists',
'5>Microbiologists',
'5>Zoologists and Wildlife Biologists',
'5>Biological Scientists, All Other',
'4>Conservation Scientists and Foresters',
'5>Conservation Scientists',
'5>Foresters',
'4>Medical Scientists',
'5>Epidemiologists',
'5>Medical Scientists, Except Epidemiologists',
'4>Life Scientists, All Other',
'3>Physical Scientists',
'4>Astronomers and Physicists',
'5>Astronomers',
'5>Physicists',
'4>Atmospheric and Space Scientists',
'4>Chemists and Materials Scientists',
'5>Chemists',
'5>Materials Scientists',
'4>Environmental Scientists and Geoscientists',
'5>Environmental Scientists and Specialists, Including Health',
'5>Geoscientists, Except Hydrologists and Geographers',
'5>Hydrologists',
'4>Physical Scientists, All Other',
'3>Social Scientists and Related Workers',
'4>Economists',
'4>Survey Researchers',
'4>Psychologists',
'5>Clinical, Counseling, and School Psychologists',
'5>Industrial-Organizational Psychologists',
'5>Psychologists, All Other',
'4>Sociologists',
'4>Urban and Regional Planners',
'4>Miscellaneous Social Scientists and Related Workers',
'5>Anthropologists and Archeologists',
'5>Geographers',
'5>Historians',
'5>Political Scientists',
'5>Social Scientists and Related Workers, All Other',
'3>Life, Physical, and Social Science Technicians',
'4>Agricultural and Food Science Technicians',
'4>Biological Technicians',
'4>Chemical Technicians',
'4>Geological and Petroleum Technicians',
'4>Nuclear Technicians',
'4>Social Science Research Assistants',
'4>Miscellaneous Life, Physical, and Social Science Technicians',
'5>Environmental Science and Protection Technicians, Including Health',
'5>Forensic Science Technicians',
'5>Forest and Conservation Technicians',
'5>Life, Physical, and Social Science Technicians, All Other',
'1>Education, Legal, Community Service, Arts, and Media Occupations',
'2>Community and Social Service Occupations',
'3>Counselors, Social Workers, and Other Community and Social Service Specialists',
'4>Counselors',
'5>Substance Abuse and Behavioral Disorder Counselors',
'5>Educational, Guidance, School, and Vocational Counselors',
'5>Marriage and Family Therapists',
'5>Mental Health Counselors',
'5>Rehabilitation Counselors',
'5>Counselors, All Other',
'4>Social Workers',
'5>Child, Family, and School Social Workers',
'5>Healthcare Social Workers',
'5>Mental Health and Substance Abuse Social Workers',
'5>Social Workers, All Other',
'4>Miscellaneous Community and Social Service Specialists',
'5>Health Educators',
'5>Probation Officers and Correctional Treatment Specialists',
'5>Social and Human Service Assistants',
'5>Community and Social Service Specialists, All Other',
'3>Religious Workers',
'4>Clergy',
'4>Directors, Religious Activities and Education',
'4>Religious Workers, All Other',
'2>Legal Occupations',
'3>Lawyers, Judges, and Related Workers',
'4>Lawyers and Judicial Law Clerks',
'5>Lawyers',
'5>Judicial Law Clerks',
'4>Judges, Magistrates, and Other Judicial Workers',
'5>Administrative Law Judges, Adjudicators, and Hearing Officers',
'5>Arbitrators, Mediators, and Conciliators',
'5>Judges, Magistrate Judges, and Magistrates',
'3>Legal Support Workers',
'4>Paralegals and Legal Assistants',
'4>Miscellaneous Legal Support Workers',
'5>Court Reporters',
'5>Title Examiners, Abstractors, and Searchers',
'5>Legal Support Workers, All Other',
'2>Education, Training, and Library Occupations',
'3>Postsecondary Teachers',
'3>Preschool, Primary, Secondary, and Special Education School Teachers',
'4>Preschool and Kindergarten Teachers',
'5>Preschool Teachers, Except Special Education',
'5>Kindergarten Teachers, Except Special Education',
'4>Elementary and Middle School Teachers',
'5>Elementary School Teachers, Except Special Education',
'5>Middle School Teachers, Except Special and Career/Technical Education',
'5>Career/Technical Education Teachers, Middle School',
'4>Secondary School Teachers',
'5>Secondary School Teachers, Except Special and Career/Technical Education',
'5>Career/Technical Education Teachers, Secondary School',
'4>Special Education Teachers',
'5>Special Education Teachers, Preschool, Kindergarten, and Elementary School',
'5>Special Education Teachers, Middle School',
'5>Special Education Teachers, Secondary School',
'3>Other Teachers and Instructors',
'4>Adult Basic and Secondary Education and Literacy Teachers and Instructors',
'4>Self-Enrichment Education Teachers',
'4>Teachers and Instructors, All Other',
'3>Librarians, Curators, and Archivists',
'4>Archivists, Curators, and Museum Technicians',
'5>Archivists',
'5>Curators',
'5>Museum Technicians and Conservators',
'4>Librarians',
'4>Library Technicians',
'3>Other Education, Training, and Library Occupations',
'4>Audio-Visual and Multimedia Collections Specialists',
'4>Farm and Home Management Advisors',
'4>Instructional Coordinators',
'4>Teacher Assistants',
'4>Education, Training, and Library Workers, All Other',
'2>Arts, Design, Entertainment, Sports, and Media Occupations',
'3>Art and Design Workers',
'4>Artists and Related Workers',
'5>Art Directors',
'5>Craft Artists',
'5>Fine Artists, Including Painters, Sculptors, and Illustrators',
'5>Multimedia Artists and Animators',
'5>Artists and Related Workers, All Other',
'4>Designers',
'5>Commercial and Industrial Designers',
'5>Fashion Designers',
'5>Floral Designers',
'5>Graphic Designers',
'5>Interior Designers',
'5>Merchandise Displayers and Window Trimmers',
'5>Set and Exhibit Designers',
'5>Designers, All Other',
'3>Entertainers and Performers, Sports and Related Workers',
'4>Actors, Producers, and Directors',
'5>Actors',
'5>Producers and Directors',
'4>Athletes, Coaches, Umpires, and Related Workers',
'5>Athletes and Sports Competitors',
'5>Coaches and Scouts',
'5>Umpires, Referees, and Other Sports Officials',
'4>Dancers and Choreographers',
'5>Dancers',
'5>Choreographers',
'4>Musicians, Singers, and Related Workers',
'5>Music Directors and Composers',
'5>Musicians and Singers',
'4>Entertainers and Performers, Sports and Related Workers, All Other',
'3>Media and Communication Workers',
'4>Announcers',
'5>Radio and Television Announcers',
'5>Public Address System and Other Announcers',
'4>News Analysts, Reporters and Correspondents',
'5>Broadcast News Analysts',
'5>Reporters and Correspondents',
'4>Public Relations Specialists',
'4>Writers and Editors',
'5>Editors',
'5>Technical Writers',
'5>Writers and Authors',
'4>Miscellaneous Media and Communication Workers',
'5>Interpreters and Translators',
'5>Media and Communication Workers, All Other',
'3>Media and Communication Equipment Workers',
'4>Broadcast and Sound Engineering Technicians and Radio Operators',
'5>Audio and Video Equipment Technicians',
'5>Broadcast Technicians',
'5>Radio Operators',
'5>Sound Engineering Technicians',
'4>Photographers',
'4>Television, Video, and Motion Picture Camera Operators and Editors',
'5>Camera Operators, Television, Video, and Motion Picture',
'5>Film and Video Editors',
'4>Media and Communication Equipment Workers, All Other',
'1>Healthcare Practitioners and Technical Occupations',
'2>Health Diagnosing and Treating Practitioners',
'3>Chiropractors',
'3>Dentists',
'4>Dentists, General',
'4>Oral and Maxillofacial Surgeons',
'4>Orthodontists',
'4>Prosthodontists',
'4>Dentists, All Other Specialists',
'3>Dietitians and Nutritionists',
'3>Optometrists',
'3>Pharmacists',
'3>Physicians and Surgeons',
'3>Physician Assistants',
'3>Podiatrists',
'3>Registered Nurses',
'3>Therapists',
'4>Occupational Therapists',
'4>Physical Therapists',
'4>Radiation Therapists',
'4>Recreational Therapists',
'4>Respiratory Therapists',
'4>Speech-Language Pathologists',
'4>Therapists, All Other',
'3>Veterinarians',
'3>Audiologists',
'3>Health Diagnosing and Treating Practitioners, All Other',
'2>Health Technologists and Technicians',
'3>Clinical Laboratory Technologists and Technicians',
'4>Medical and Clinical Laboratory Technologists',
'4>Medical and Clinical Laboratory Technicians',
'3>Dental Hygienists',
'3>Diagnostic Related Technologists and Technicians',
'4>Cardiovascular Technologists and Technicians',
'4>Diagnostic Medical Sonographers',
'4>Nuclear Medicine Technologists',
'4>Radiologic Technologists and Technicians',
'3>Emergency Medical Technicians and Paramedics',
'3>Health Practitioner Support Technologists and Technicians',
'4>Dietetic Technicians',
'4>Pharmacy Technicians',
'4>Psychiatric Technicians',
'4>Respiratory Therapy Technicians',
'4>Surgical Technologists',
'4>Veterinary Technologists and Technicians',
'3>Licensed Practical and Licensed Vocational Nurses',
'3>Medical Records and Health Information Technicians',
'3>Opticians, Dispensing',
'3>Orthotists and Prosthetists',
'3>Health Technologists and Technicians, All Other',
'2>Other Healthcare Practitioners and Technical Occupations',
'3>Occupational Health and Safety Specialists and Technicians',
'4>Occupational Health and Safety Specialists',
'4>Occupational Health and Safety Technicians',
'3>Miscellaneous Health Practitioners and Technical Workers',
'4>Athletic Trainers',
'4>Healthcare Practitioners and Technical Workers, All Other',
'1>Service Occupations',
'2>Healthcare Support Occupations',
'3>Nursing, Psychiatric, and Home Health Aides',
'4>Home Health Aides',
'4>Nursing Aides, Orderlies, and Attendants',
'4>Psychiatric Aides',
'3>Occupational Therapy and Physical Therapist Assistants and Aides',
'4>Occupational Therapy Assistants and Aides',
'5>Occupational Therapy Assistants',
'5>Occupational Therapy Aides',
'4>Physical Therapist Assistants and Aides',
'5>Physical Therapist Assistants',
'5>Physical Therapist Aides',
'3>Other Healthcare Support Occupations',
'4>Massage Therapists',
'4>Miscellaneous Healthcare Support Occupations',
'5>Dental Assistants',
'5>Medical Assistants',
'5>Medical Equipment Preparers',
'5>Medical Transcriptionists',
'5>Pharmacy Aides',
'5>Veterinary Assistants and Laboratory Animal Caretakers',
'5>Healthcare Support Workers, All Other',
'2>Protective Service Occupations',
'3>Supervisors of Protective Service Workers',
'4>First-Line Supervisors of Law Enforcement Workers',
'5>First-Line Supervisors of Correctional Officers',
'5>First-Line Supervisors of Police and Detectives',
'4>First-Line Supervisors of Fire Fighting and Prevention Workers',
'4>First-Line Supervisors of Protective Service Workers, All Other',
'3>Fire Fighting and Prevention Workers',
'4>Firefighters',
'4>Fire Inspectors',
'5>Fire Inspectors and Investigators',
'5>Forest Fire Inspectors and Prevention Specialists',
'3>Law Enforcement Workers',
'4>Bailiffs, Correctional Officers, and Jailers',
'5>Bailiffs',
'5>Correctional Officers and Jailers',
'4>Detectives and Criminal Investigators',
'4>Fish and Game Wardens',
'4>Parking Enforcement Workers',
'4>Police Officers',
'5>Police and Sheriff\'s Patrol Officers',
'5>Transit and Railroad Police',
'3>Other Protective Service Workers',
'4>Animal Control Workers',
'4>Private Detectives and Investigators',
'4>Security Guards and Gaming Surveillance Officers',
'5>Gaming Surveillance Officers and Gaming Investigators',
'5>Security Guards',
'4>Miscellaneous Protective Service Workers',
'5>Crossing Guards',
'5>Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers',
'5>Transportation Security Screeners (Federal Only)',
'5>Protective Service Workers, All Other',
'2>Food Preparation and Serving Related Occupations',
'3>Supervisors of Food Preparation and Serving Workers',
'4>Chefs and Head Cooks',
'4>First-Line Supervisors of Food Preparation and Serving Workers',
'3>Cooks and Food Preparation Workers',
'4>Cooks',
'5>Cooks, Fast Food',
'5>Cooks, Institution and Cafeteria',
'5>Cooks, Private Household',
'5>Cooks, Restaurant',
'5>Cooks, Short Order',
'5>Cooks, All Other',
'4>Food Preparation Workers',
'3>Food and Beverage Serving Workers',
'4>Bartenders',
'4>Fast Food and Counter Workers',
'5>Combined Food Preparation and Serving Workers, Including Fast Food',
'5>Counter Attendants, Cafeteria, Food Concession, and Coffee Shop',
'4>Waiters and Waitresses',
'4>Food Servers, Nonrestaurant',
'3>Other Food Preparation and Serving Related Workers',
'4>Dining Room and Cafeteria Attendants and Bartender Helpers',
'4>Dishwashers',
'4>Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop',
'4>Food Preparation and Serving Related Workers, All Other',
'2>Building and Grounds Cleaning and Maintenance Occupations',
'3>Supervisors of Building and Grounds Cleaning and Maintenance Workers',
'4>First-Line Supervisors of Housekeeping and Janitorial Workers',
'4>First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers',
'3>Building Cleaning and Pest Control Workers',
'4>Building Cleaning Workers',
'5>Janitors and Cleaners, Except Maids and Housekeeping Cleaners',
'5>Maids and Housekeeping Cleaners',
'5>Building Cleaning Workers, All Other',
'4>Pest Control Workers',
'3>Grounds Maintenance Workers',
'4>Landscaping and Groundskeeping Workers',
'4>Pesticide Handlers, Sprayers, and Applicators, Vegetation',
'4>Tree Trimmers and Pruners',
'4>Grounds Maintenance Workers, All Other',
'2>Personal Care and Service Occupations',
'3>Supervisors of Personal Care and Service Workers',
'4>First-Line Supervisors of Gaming Workers',
'5>Gaming Supervisors',
'5>Slot Supervisors',
'4>First-Line Supervisors of Personal Service Workers',
'3>Animal Care and Service Workers',
'4>Animal Trainers',
'4>Nonfarm Animal Caretakers',
'3>Entertainment Attendants and Related Workers',
'4>Gaming Services Workers',
'5>Gaming Dealers',
'5>Gaming and Sports Book Writers and Runners',
'5>Gaming Service Workers, All Other',
'4>Motion Picture Projectionists',
'4>Ushers, Lobby Attendants, and Ticket Takers',
'4>Miscellaneous Entertainment Attendants and Related Workers',
'5>Amusement and Recreation Attendants',
'5>Costume Attendants',
'5>Locker Room, Coatroom, and Dressing Room Attendants',
'5>Entertainment Attendants and Related Workers, All Other',
'3>Funeral Service Workers',
'4>Embalmers',
'4>Funeral Attendants',
'4>Funeral Service Managers, Directors, Morticians, and Undertakers',
'3>Personal Appearance Workers',
'4>Barbers, Hairdressers, Hairstylists and Cosmetologists',
'5>Barbers',
'5>Hairdressers, Hairstylists, and Cosmetologists',
'4>Miscellaneous Personal Appearance Workers',
'5>Makeup Artists, Theatrical and Performance',
'5>Manicurists and Pedicurists',
'5>Shampooers',
'5>Skincare Specialists',
'3>Baggage Porters, Bellhops, and Concierges',
'4>Baggage Porters and Bellhops',
'4>Concierges',
'3>Tour and Travel Guides',
'4>Tour Guides and Escorts',
'4>Travel Guides',
'3>Other Personal Care and Service Workers',
'4>Childcare Workers',
'4>Personal Care Aides',
'4>Recreation and Fitness Workers',
'5>Fitness Trainers and Aerobics Instructors',
'5>Recreation Workers',
'4>Residential Advisors',
'4>Personal Care and Service Workers, All Other',
'1>Sales and Related Occupations',
'2>Supervisors of Sales Workers',
'3>First-Line Supervisors of Retail Sales Workers',
'3>First-Line Supervisors of Non-Retail Sales Workers',
'2>Retail Sales Workers',
'3>Cashiers',
'4>Cashiers',
'4>Gaming Change Persons and Booth Cashiers',
'3>Counter and Rental Clerks and Parts Salespersons',
'4>Counter and Rental Clerks',
'4>Parts Salespersons',
'3>Retail Salespersons',
'2>Sales Representatives, Services',
'3>Advertising Sales Agents',
'3>Insurance Sales Agents',
'3>Securities, Commodities, and Financial Services Sales Agents',
'3>Travel Agents',
'3>Sales Representatives, Services, All Other',
'2>Sales Representatives, Wholesale and Manufacturing',
'3>Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
'3>Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
'2>Other Sales and Related Workers',
'3>Models, Demonstrators, and Product Promoters',
'4>Demonstrators and Product Promoters',
'4>Models',
'3>Real Estate Brokers and Sales Agents',
'4>Real Estate Brokers',
'4>Real Estate Sales Agents',
'3>Sales Engineers',
'3>Telemarketers',
'3>Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
'3>Sales and Related Workers, All Other',
'1>Office and Administrative Support Occupations',
'2>Supervisors of Office and Administrative Support Workers',
'3>First-Line Supervisors of Office and Administrative Support Workers',
'2>Communications Equipment Operators',
'3>Switchboard Operators, Including Answering Service',
'3>Telephone Operators',
'3>Communications Equipment Operators, All Other',
'2>Financial Clerks',
'3>Bill and Account Collectors',
'3>Billing and Posting Clerks',
'3>Bookkeeping, Accounting, and Auditing Clerks',
'3>Gaming Cage Workers',
'3>Payroll and Timekeeping Clerks',
'3>Procurement Clerks',
'3>Tellers',
'2>Information and Record Clerks',
'3>Brokerage Clerks',
'3>Correspondence Clerks',
'3>Court, Municipal, and License Clerks',
'3>Credit Authorizers, Checkers, and Clerks',
'3>Customer Service Representatives',
'3>Eligibility Interviewers, Government Programs',
'3>File Clerks',
'3>Hotel, Motel, and Resort Desk Clerks',
'3>Interviewers, Except Eligibility and Loan',
'3>Library Assistants, Clerical',
'3>Loan Interviewers and Clerks',
'3>New Accounts Clerks',
'3>Order Clerks',
'3>Human Resources Assistants, Except Payroll and Timekeeping',
'3>Receptionists and Information Clerks',
'3>Reservation and Transportation Ticket Agents and Travel Clerks',
'3>Information and Record Clerks, All Other',
'2>Material Recording, Scheduling, Dispatching, and Distributing Workers',
'3>Cargo and Freight Agents',
'3>Couriers and Messengers',
'3>Dispatchers',
'4>Police, Fire, and Ambulance Dispatchers',
'4>Dispatchers, Except Police, Fire, and Ambulance',
'3>Meter Readers, Utilities',
'3>Postal Service Workers',
'4>Postal Service Clerks',
'4>Postal Service Mail Carriers',
'4>Postal Service Mail Sorters, Processors, and Processing Machine Operators',
'3>Production, Planning, and Expediting Clerks',
'3>Shipping, Receiving, and Traffic Clerks',
'3>Stock Clerks and Order Fillers',
'3>Weighers, Measurers, Checkers, and Samplers, Recordkeeping',
'2>Secretaries and Administrative Assistants',
'3>Executive Secretaries and Executive Administrative Assistants',
'3>Legal Secretaries',
'3>Medical Secretaries',
'3>Secretaries and Administrative Assistants, Except Legal, Medical, and Executive',
'2>Other Office and Administrative Support Workers',
'3>Computer Operators',
'3>Data Entry and Information Processing Workers',
'4>Data Entry Keyers',
'4>Word Processors and Typists',
'3>Desktop Publishers',
'3>Insurance Claims and Policy Processing Clerks',
'3>Mail Clerks and Mail Machine Operators, Except Postal Service',
'3>Office Clerks, General',
'3>Office Machine Operators, Except Computer',
'3>Proofreaders and Copy Markers',
'3>Statistical Assistants',
'3>Office and Administrative Support Workers, All Other',
'1>Farming, Fishing, and Forestry Occupations',
'2>Supervisors of Farming, Fishing, and Forestry Workers',
'3>First-Line Supervisors of Farming, Fishing, and Forestry Workers',
'2>Agricultural Workers',
'3>Agricultural Inspectors',
'3>Animal Breeders',
'3>Graders and Sorters, Agricultural Products',
'3>Miscellaneous Agricultural Workers',
'2>Fishing and Hunting Workers',
'3>Fishers and Related Fishing Workers',
'2>Forest, Conservation, and Logging Workers',
'3>Forest and Conservation Workers',
'3>Logging Workers',
'4>Fallers',
'4>Logging Equipment Operators',
'4>Log Graders and Scalers',
'4>Logging Workers, All Other',
'1>Construction and Extraction Occupations',
'2>Supervisors of Construction and Extraction Workers',
'3>First-Line Supervisors of Construction Trades and Extraction Workers',
'2>Construction Trades Workers',
'3>Boilermakers',
'3>Brickmasons, Blockmasons, and Stonemasons',
'4>Brickmasons and Blockmasons',
'4>Stonemasons',
'3>Carpenters',
'3>Carpet, Floor, and Tile Installers and Finishers',
'4>Carpet Installers',
'4>Floor Layers, Except Carpet, Wood, and Hard Tiles',
'4>Floor Sanders and Finishers',
'4>Tile and Marble Setters',
'3>Cement Masons, Concrete Finishers, and Terrazzo Workers',
'4>Cement Masons and Concrete Finishers',
'4>Terrazzo Workers and Finishers',
'3>Construction Laborers',
'3>Construction Equipment Operators',
'4>Paving, Surfacing, and Tamping Equipment Operators',
'4>Pile-Driver Operators',
'4>Operating Engineers and Other Construction Equipment Operators',
'3>Drywall Installers, Ceiling Tile Installers, and Tapers',
'4>Drywall and Ceiling Tile Installers',
'4>Tapers',
'3>Electricians',
'3>Glaziers',
'3>Insulation Workers',
'4>Insulation Workers, Floor, Ceiling, and Wall',
'4>Insulation Workers, Mechanical',
'3>Painters and Paperhangers',
'4>Painters, Construction and Maintenance',
'4>Paperhangers',
'3>Pipelayers, Plumbers, Pipefitters, and Steamfitters',
'4>Pipelayers',
'4>Plumbers, Pipefitters, and Steamfitters',
'3>Plasterers and Stucco Masons',
'3>Reinforcing Iron and Rebar Workers',
'3>Roofers',
'3>Sheet Metal Workers',
'3>Structural Iron and Steel Workers',
'2>Helpers, Construction Trades',
'3>Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters',
'3>Helpers--Carpenters',
'3>Helpers--Electricians',
'3>Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons',
'3>Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters',
'3>Helpers--Roofers',
'3>Helpers, Construction Trades, All Other',
'2>Other Construction and Related Workers',
'3>Construction and Building Inspectors',
'3>Elevator Installers and Repairers',
'3>Fence Erectors',
'3>Hazardous Materials Removal Workers',
'3>Highway Maintenance Workers',
'3>Rail-Track Laying and Maintenance Equipment Operators',
'3>Septic Tank Servicers and Sewer Pipe Cleaners',
'3>Miscellaneous Construction and Related Workers',
'4>Segmental Pavers',
'3>Construction and Related Workers, All Other',
'2>Extraction Workers',
'3>Derrick, Rotary Drill, and Service Unit Operators, Oil, Gas, and Mining',
'4>Derrick Operators, Oil and Gas',
'4>Rotary Drill Operators, Oil and Gas',
'4>Service Unit Operators, Oil, Gas, and Mining',
'3>Earth Drillers, Except Oil and Gas',
'3>Explosives Workers, Ordnance Handling Experts, and Blasters',
'3>Mining Machine Operators',
'4>Continuous Mining Machine Operators',
'4>Mine Cutting and Channeling Machine Operators',
'4>Mining Machine Operators, All Other',
'3>Rock Splitters, Quarry',
'3>Roof Bolters, Mining',
'3>Roustabouts, Oil and Gas',
'3>Helpers--Extraction Workers',
'3>Extraction Workers, All Other',
'1>Installation, Maintenance, and Repair Occupations',
'2>Supervisors of Installation, Maintenance, and Repair Workers',
'3>First-Line Supervisors of Mechanics, Installers, and Repairers',
'2>Electrical and Electronic Equipment Mechanics, Installers, and Repairers',
'3>Computer, Automated Teller, and Office Machine Repairers',
'3>Radio and Telecommunications Equipment Installers and Repairers',
'4>Radio, Cellular, and Tower Equipment Installers and Repairs',
'4>Telecommunications Equipment Installers and Repairers, Except Line Installers',
'3>Miscellaneous Electrical and Electronic Equipment Mechanics, Installers, and Repairers',
'4>Avionics Technicians',
'4>Electric Motor, Power Tool, and Related Repairers',
'4>Electrical and Electronics Installers and Repairers, Transportation Equipment',
'4>Electrical and Electronics Repairers, Commercial and Industrial Equipment',
'4>Electrical and Electronics Repairers, Powerhouse, Substation, and Relay',
'4>Electronic Equipment Installers and Repairers, Motor Vehicles',
'4>Electronic Home Entertainment Equipment Installers and Repairers',
'4>Security and Fire Alarm Systems Installers',
'2>Vehicle and Mobile Equipment Mechanics, Installers, and Repairers',
'3>Aircraft Mechanics and Service Technicians',
'3>Automotive Technicians and Repairers',
'4>Automotive Body and Related Repairers',
'4>Automotive Glass Installers and Repairers',
'4>Automotive Service Technicians and Mechanics',
'3>Bus and Truck Mechanics and Diesel Engine Specialists',
'3>Heavy Vehicle and Mobile Equipment Service Technicians and Mechanics',
'4>Farm Equipment Mechanics and Service Technicians',
'4>Mobile Heavy Equipment Mechanics, Except Engines',
'4>Rail Car Repairers',
'3>Small Engine Mechanics',
'4>Motorboat Mechanics and Service Technicians',
'4>Motorcycle Mechanics',
'4>Outdoor Power Equipment and Other Small Engine Mechanics',
'3>Miscellaneous Vehicle and Mobile Equipment Mechanics, Installers, and Repairers',
'4>Bicycle Repairers',
'4>Recreational Vehicle Service Technicians',
'4>Tire Repairers and Changers',
'2>Other Installation, Maintenance, and Repair Occupations',
'3>Control and Valve Installers and Repairers',
'4>Mechanical Door Repairers',
'4>Control and Valve Installers and Repairers, Except Mechanical Door',
'3>Heating, Air Conditioning, and Refrigeration Mechanics and Installers',
'3>Home Appliance Repairers',
'3>Industrial Machinery Installation, Repair, and Maintenance Workers',
'4>Industrial Machinery Mechanics',
'4>Maintenance Workers, Machinery',
'4>Millwrights',
'4>Refractory Materials Repairers, Except Brickmasons',
'3>Line Installers and Repairers',
'4>Electrical Power-Line Installers and Repairers',
'4>Telecommunications Line Installers and Repairers',
'3>Precision Instrument and Equipment Repairers',
'4>Camera and Photographic Equipment Repairers',
'4>Medical Equipment Repairers',
'4>Musical Instrument Repairers and Tuners',
'4>Watch Repairers',
'4>Precision Instrument and Equipment Repairers, All Other',
'3>Maintenance and Repair Workers, General',
'3>Miscellaneous Installation, Maintenance, and Repair Workers',
'4>Coin, Vending, and Amusement Machine Servicers and Repairers',
'4>Commercial Divers',
'4>Fabric Menders, Except Garment',
'4>Locksmiths and Safe Repairers',
'4>Manufactured Building and Mobile Home Installers',
'4>Riggers',
'4>Signal and Track Switch Repairers',
'4>Helpers--Installation, Maintenance, and Repair Workers',
'3>Installation, Maintenance, and Repair Workers, All Other',
'1>Production Occupations',
'2>Supervisors of Production Workers',
'3>First-Line Supervisors of Production and Operating Workers',
'2>Assemblers and Fabricators',
'3>Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
'3>Electrical, Electronics, and Electromechanical Assemblers',
'4>Coil Winders, Tapers, and Finishers',
'4>Electrical and Electronic Equipment Assemblers',
'4>Electromechanical Equipment Assemblers',
'3>Engine and Other Machine Assemblers',
'3>Structural Metal Fabricators and Fitters',
'3>Miscellaneous Assemblers and Fabricators',
'4>Fiberglass Laminators and Fabricators',
'4>Team Assemblers',
'4>Timing Device Assemblers and Adjusters',
'4>Assemblers and Fabricators, All Other',
'2>Food Processing Workers',
'3>Bakers',
'3>Butchers and Other Meat, Poultry, and Fish Processing Workers',
'4>Butchers and Meat Cutters',
'4>Meat, Poultry, and Fish Cutters and Trimmers',
'4>Slaughterers and Meat Packers',
'3>Miscellaneous Food Processing Workers',
'4>Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders',
'4>Food Batchmakers',
'4>Food Cooking Machine Operators and Tenders',
'2>Metal Workers and Plastic Workers',
'3>Computer Control Programmers and Operators',
'4>Computer-Controlled Machine Tool Operators, Metal and Plastic',
'4>Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic',
'3>Forming Machine Setters, Operators, and Tenders, Metal and Plastic',
'4>Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic',
'4>Forging Machine Setters, Operators, and Tenders, Metal and Plastic',
'4>Rolling Machine Setters, Operators, and Tenders, Metal and Plastic',
'3>Machine Tool Cutting Setters, Operators, and Tenders, Metal and Plastic',
'4>Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic',
'4>Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
'4>Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
'4>Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
'4>Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic',
'3>Machinists',
'3>Metal Furnace Operators, Tenders, Pourers, and Casters',
'4>Metal-Refining Furnace Operators and Tenders',
'4>Pourers and Casters, Metal',
'3>Model Makers and Patternmakers, Metal and Plastic',
'4>Model Makers, Metal and Plastic',
'4>Patternmakers, Metal and Plastic',
'3>Molders and Molding Machine Setters, Operators, and Tenders, Metal and Plastic',
'4>Foundry Mold and Coremakers',
'4>Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic',
'3>Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
'3>Tool and Die Makers',
'3>Welding, Soldering, and Brazing Workers',
'4>Welders, Cutters, Solderers, and Brazers',
'4>Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders',
'3>Miscellaneous Metal Workers and Plastic Workers',
'4>Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic',
'4>Layout Workers, Metal and Plastic',
'4>Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic',
'4>Tool Grinders, Filers, and Sharpeners',
'4>Metal Workers and Plastic Workers, All Other',
'2>Printing Workers',
'3>Prepress Technicians and Workers',
'3>Printing Press Operators',
'3>Print Binding and Finishing Workers',
'2>Textile, Apparel, and Furnishings Workers',
'3>Laundry and Dry-Cleaning Workers',
'3>Pressers, Textile, Garment, and Related Materials',
'3>Sewing Machine Operators',
'3>Shoe and Leather Workers',
'4>Shoe and Leather Workers and Repairers',
'4>Shoe Machine Operators and Tenders',
'3>Tailors, Dressmakers, and Sewers',
'4>Sewers, Hand',
'4>Tailors, Dressmakers, and Custom Sewers',
'3>Textile Machine Setters, Operators, and Tenders',
'4>Textile Bleaching and Dyeing Machine Operators and Tenders',
'4>Textile Cutting Machine Setters, Operators, and Tenders',
'4>Textile Knitting and Weaving Machine Setters, Operators, and Tenders',
'4>Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders',
'3>Miscellaneous Textile, Apparel, and Furnishings Workers',
'4>Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers',
'4>Fabric and Apparel Patternmakers',
'4>Upholsterers',
'4>Textile, Apparel, and Furnishings Workers, All Other',
'2>Woodworkers',
'3>Cabinetmakers and Bench Carpenters',
'3>Furniture Finishers',
'3>Model Makers and Patternmakers, Wood',
'4>Model Makers, Wood',
'4>Patternmakers, Wood',
'3>Woodworking Machine Setters, Operators, and Tenders',
'4>Sawing Machine Setters, Operators, and Tenders, Wood',
'4>Woodworking Machine Setters, Operators, and Tenders, Except Sawing',
'3>Woodworkers, All Other',
'2>Plant and System Operators',
'3>Power Plant Operators, Distributors, and Dispatchers',
'4>Nuclear Power Reactor Operators',
'4>Power Distributors and Dispatchers',
'4>Power Plant Operators',
'3>Stationary Engineers and Boiler Operators',
'3>Water and Wastewater Treatment Plant and System Operators',
'3>Miscellaneous Plant and System Operators',
'4>Chemical Plant and System Operators',
'4>Gas Plant Operators',
'4>Petroleum Pump System Operators, Refinery Operators, and Gaugers',
'4>Plant and System Operators, All Other',
'2>Other Production Occupations',
'3>Chemical Processing Machine Setters, Operators, and Tenders',
'4>Chemical Equipment Operators and Tenders',
'4>Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders',
'3>Crushing, Grinding, Polishing, Mixing, and Blending Workers',
'4>Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders',
'4>Grinding and Polishing Workers, Hand',
'4>Mixing and Blending Machine Setters, Operators, and Tenders',
'3>Cutting Workers',
'4>Cutters and Trimmers, Hand',
'4>Cutting and Slicing Machine Setters, Operators, and Tenders',
'3>Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders',
'3>Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders',
'3>Inspectors, Testers, Sorters, Samplers, and Weighers',
'3>Jewelers and Precious Stone and Metal Workers',
'3>Medical, Dental, and Ophthalmic Laboratory Technicians',
'4>Dental Laboratory Technicians',
'4>Medical Appliance Technicians',
'4>Ophthalmic Laboratory Technicians',
'3>Packaging and Filling Machine Operators and Tenders',
'3>Painting Workers',
'4>Coating, Painting, and Spraying Machine Setters, Operators, and Tenders',
'4>Painters, Transportation Equipment',
'4>Painting, Coating, and Decorating Workers',
'3>Semiconductor Processors',
'3>Photographic Process Workers and Processing Machine Operators',
'3>Miscellaneous Production Workers',
'4>Adhesive Bonding Machine Operators and Tenders',
'4>Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders',
'4>Cooling and Freezing Equipment Operators and Tenders',
'4>Etchers and Engravers',
'4>Molders, Shapers, and Casters, Except Metal and Plastic',
'4>Paper Goods Machine Setters, Operators, and Tenders',
'4>Tire Builders',
'4>Helpers--Production Workers',
'3>Production Workers, All Other',
'1>Transportation and Material Moving Occupations',
'2>Supervisors of Transportation and Material Moving Workers',
'3>Aircraft Cargo Handling Supervisors',
'3>First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand',
'3>First-Line Supervisors of Transportation and Material-Moving Machine and Vehicle Operators',
'2>Air Transportation Workers',
'3>Aircraft Pilots and Flight Engineers',
'4>Airline Pilots, Copilots, and Flight Engineers',
'4>Commercial Pilots',
'3>Air Traffic Controllers and Airfield Operations Specialists',
'4>Air Traffic Controllers',
'4>Airfield Operations Specialists',
'3>Flight Attendants',
'2>Motor Vehicle Operators',
'3>Ambulance Drivers and Attendants, Except Emergency Medical Technicians',
'3>Bus Drivers',
'4>Bus Drivers, Transit and Intercity',
'4>Bus Drivers, School or Special Client',
'3>Driver/Sales Workers and Truck Drivers',
'4>Driver/Sales Workers',
'4>Heavy and Tractor-Trailer Truck Drivers',
'4>Light Truck or Delivery Services Drivers',
'3>Taxi Drivers and Chauffeurs',
'3>Motor Vehicle Operators, All Other',
'2>Rail Transportation Workers',
'3>Locomotive Engineers and Operators',
'4>Locomotive Engineers',
'4>Locomotive Firers',
'4>Rail Yard Engineers, Dinkey Operators, and Hostlers',
'3>Railroad Brake, Signal, and Switch Operators',
'3>Railroad Conductors and Yardmasters',
'3>Subway and Streetcar Operators',
'3>Rail Transportation Workers, All Other',
'2>Water Transportation Workers',
'3>Sailors and Marine Oilers',
'3>Ship and Boat Captains and Operators',
'4>Captains, Mates, and Pilots of Water Vessels',
'4>Motorboat Operators',
'3>Ship Engineers',
'2>Other Transportation Workers',
'3>Bridge and Lock Tenders',
'3>Parking Lot Attendants',
'3>Automotive and Watercraft Service Attendants',
'3>Traffic Technicians',
'3>Transportation Inspectors',
'3>Transportation Attendants, Except Flight Attendants',
'3>Transportation Workers, All Other',
'2>Material Moving Workers',
'3>Conveyor Operators and Tenders',
'3>Crane and Tower Operators',
'3>Dredge, Excavating, and Loading Machine Operators',
'4>Dredge Operators',
'4>Excavating and Loading Machine and Dragline Operators',
'4>Loading Machine Operators, Underground Mining',
'3>Hoist and Winch Operators',
'3>Industrial Truck and Tractor Operators',
'3>Laborers and Material Movers, Hand',
'4>Cleaners of Vehicles and Equipment',
'4>Laborers and Freight, Stock, and Material Movers, Hand',
'4>Machine Feeders and Offbearers',
'4>Packers and Packagers, Hand',
'3>Pumping Station Operators',
'4>Gas Compressor and Gas Pumping Station Operators',
'4>Pump Operators, Except Wellhead Pumpers',
'4>Wellhead Pumpers',
'3>Refuse and Recyclable Material Collectors',
'3>Mine Shuttle Car Operators',
'3>Tank Car, Truck, and Ship Loaders',
'3>Material Moving Workers, All Other']

def level(inString):
	return int(inString[0])

def findParent(index):
	myString = data[index]
	myLev = level(myString)
	options = data[0:index]
	if myLev==0:
		parent = 'null'		
	else:
		for item in reversed(options):
			testLevel = level(item)
			print testLevel
			if testLevel<myLev:
				parent = item[2:]
				break
	print data[index],myLev,options,parent

findParent(3)

def rewrite():
	for i in range(len(data)):
		level = int(data[i][0])
		if level > 0:
			for i2 in reversed(range(i)):
				testLevel = int(data[i2][0])
				if testLevel < level:
					parent = data[i2][2:]
					break
		else:
			parent = 'null'
		print data[i][2:] + '\t' + parent

rewrite()